# Generated by Django 3.2.23 on 2023-11-25 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Civil Servant', 'Civil Servant'), ('Business', 'Business')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='CarRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drivers_license', models.CharField(max_length=50)),
                ('vehicle_insurance', models.CharField(max_length=50, verbose_name='Vehicle Insurance Number')),
                ('nin', models.CharField(max_length=15, verbose_name='NIN')),
                ('proof_address', models.CharField(max_length=50)),
                ('tin', models.CharField(max_length=15, verbose_name='Tax Identification Number')),
                ('custom_clearance', models.ImageField(upload_to='customclearance')),
                ('vehicle_engine', models.CharField(max_length=15, verbose_name='Vehicle Engine Number')),
                ('proof_of_ownership', models.ImageField(upload_to='proof')),
                ('passport', models.ImageField(upload_to=None, verbose_name='Two passport of ownership')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
